networks:
  network:
    name: ${PROJECT_NAME}-network

services:
  jaeger:
    container_name: ${PROJECT_NAME}-jaeger
    image: jaegertracing/all-in-one:1.60
    hostname: jaeger
    ports:
      - "${JAEGER_LOCAL_WEB_PORT}:16686"
      - "${JAEGER_LOCAL_GRPC_PORT}:4317"
      - "${JAEGER_LOCAL_HTTP_PORT}:4318"
    environment:
      - LOG_LEVEL=debug
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - network
    restart: unless-stopped
